### ISSUE TITLE
This event has sold out online

### ISSUE THREAD

**Issue by VellalaVineethKumar** [rmcelreath/stat_rethinking_2022#1]
Hi Richard McElreath
I am a recent undergrad with an interest in applied statistics. I am willing to learn more about statistics but the website says "This event has sold out online" Can you please let me in to attend your lectures?

**Comment by raphaelmartin** [comment]
> Aaaaand it's sold out. Sorry there aren't more spots. Had to give priority to my 
@MPI_EVA_Leipzig
 and 
@idiv
 peeps.
Will post lecture links here as they become available.

https://twitter.com/rlmcelreath/status/1459148324091703298

**Comment by dendrobiummoniliforme** [comment]
Added an MR for this: https://github.com/rmcelreath/stat_rethinking_2022/pull/2 :)
