### ISSUE TITLE
typo in 03_howell_new_weight_model.r

### ISSUE THREAD

**Issue by wesslen** [rmcelreath/stat_rethinking_2022#10]
Should `m0` on lines 135 and 140 of [03_howell_new_weight_model.r](https://github.com/rmcelreath/stat_rethinking_2022/blob/main/scripts_animation/03_howell_new_weight_model.r) be `m_adults`?

`m0` isn't defined in the code.

Thank you!

**Comment by rmcelreath** [comment]
Thanks for spotting that
