### ISSUE TITLE
many base R plots not rendering scatterplot points in slides

### ISSUE THREAD

**Issue by wesslen** [rmcelreath/stat_rethinking_2022#13]
FYI many base R scatterplots are not rendering in the pdf slides.

Examples:
* [Lecture 3 slides 25-28](https://speakerdeck.com/rmcelreath/statistical-rethinking-2022-lecture-03?slide=25)
* [Lecture 3 slide 38](https://speakerdeck.com/rmcelreath/statistical-rethinking-2022-lecture-03?slide=38)
* [Lecture 3 slide 40](https://speakerdeck.com/rmcelreath/statistical-rethinking-2022-lecture-03?slide=40)
* [Lecture 4 slide 6](https://speakerdeck.com/rmcelreath/statistical-rethinking-2022-lecture-04?slide=6)
* [Lecture 4 slide 8](https://speakerdeck.com/rmcelreath/statistical-rethinking-2022-lecture-04?slide=8)
* [Lecture 5 slide 6](https://speakerdeck.com/rmcelreath/statistical-rethinking-2022-lecture-05?slide=6)
* [Lecture 5 slides 13-4](https://speakerdeck.com/rmcelreath/statistical-rethinking-2022-lecture-05?slide=13)
* [Lecture 6 slide 87](https://speakerdeck.com/rmcelreath/statistical-rethinking-2022-lecture-06?slide=87)

List above isn't all slides that have issues but a few for illustrative.

**Comment by rmcelreath** [comment]
I think it's just a browser issue. Try downloading the PDF instead of viewing in browser.

**Comment by wesslen** [comment]
Thank you!
