### ISSUE TITLE
error still in Lecture 9 marginalized effect example?

### ISSUE THREAD

**Issue by benslack19** [rmcelreath/stat_rethinking_2022#14]
Hi, I think you said that the error from lecture 9 is fixed, but I'm wondering if an error is still there on slide 75 and 76?

For example on slide 75, there's this code where `link` refers to model `m2`:

```
# simulate as if all apps from women
p_G1 <- link(m2,data=list(
D=rep(1:6,times=apps_per_dept),
N=rep(1,total_apps),
G=rep(1,total_apps)))
```

But in the [lecture code](https://github.com/rmcelreath/stat_rethinking_2022/blob/main/scripts_animation/09_binomial_GLMs.r), the model now refers to **`mGD`**.

```
# simulate as if all apps from women
p_G1 <- link(mGD,data=list(
    D=rep(1:6,times=apps_per_dept),
    N=rep(1,total_apps),
    G=rep(1,total_apps)))
```

**Comment by rmcelreath** [comment]
mGD is right. See https://github.com/rmcelreath/stat_rethinking_2022/commit/2542781137bc9033294b651132dcf666e1d8112f

**Comment by benslack19** [comment]
Ok thanks. To confirm, the [slide](https://speakerdeck.com/rmcelreath/statistical-rethinking-2022-lecture-09?slide=75) still needs to be correctedl?
