### ISSUE TITLE
Unable to replicate a plot in Lecture 09

### ISSUE THREAD

**Issue by ellen-ying** [rmcelreath/stat_rethinking_2022#18]
I was unable to replicate the plot of the hypothetical effect of manipulating the perception of applicants' gender. Using the code provided in the repository, I got something like this:
<img width="576" alt="image" src="https://user-images.githubusercontent.com/91786091/173979368-0a2b620d-7e79-4d77-a345-aaca573eec80.png">
Instead of the one shown in the lecture:
<img width="455" alt="image" src="https://user-images.githubusercontent.com/91786091/173979401-586c9f9a-38b4-430c-823b-fda5846b0fe2.png">

**Comment by rmcelreath** [comment]
The code in the repo is correct.
