### ISSUE TITLE
which book to buy?

### ISSUE THREAD

**Issue by Sandy4321** [rmcelreath/stat_rethinking_2022#5]
which book to buy?

Statistical Rethinking: A Bayesian Course with Examples in R and STAN Hardcover – March 16 2020
by Richard McElreath  (Author) ?
https://www.amazon.ca/Statistical-Rethinking-Bayesian-Course-Examples/dp/036713991X/ref=sr_1_2?gclid=Cj0KCQiA8vSOBhCkARIsAGdp6RRjxXH1pEPmwImkgZcRpJt3Dg4TtOtwemUP5kBetPmUsQKQW2WtA2IaAnkWEALw_wcB&hvadid=229990286577&hvdev=c&hvlocphy=9000920&hvnetw=g&hvqmt=e&hvrand=14759278627849499121&hvtargid=kwd-300572196203&hydadcr=3317_10311015&keywords=statistical+rethinking&qid=1641911963&sr=8-2

**Comment by rmcelreath** [comment]
2nd edition https://www.routledge.com/Statistical-Rethinking-A-Bayesian-Course-with-Examples-in-R-and-STAN/McElreath/p/book/9780367139919

If you are enrolled in the course, you received a PDF of the 2nd edition

**Comment by Sandy4321** [comment]
If you are enrolled in the course, you received a PDF of the 2nd edition
I am not from your university
